/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [Report_Date]
      ,[Account_Number]
      ,[Card_Number]
      ,[Customer_Name]
      ,[Seller]
      ,[Business]
      ,[Base_Portfolio]
      ,[Reporting_Portfolio]
      ,[GCV]
      ,[PV]
      ,[Outstanding_Balance]
      ,[Outstanding_Principal]
      ,[Stage]
      ,[Write_Off_Year]
      ,[Write_Off_Month]
      ,[Load_Date]
      ,[Last_Call_Date]
      ,[Call_Time]
      ,[Days_Last_Called]
      ,[Last_Called_Date_Bucket]
      ,[Last_Called_By]
      ,[Last_Call_Outcome]
      ,[Last_Call_Disposition]
      ,[Call_Type]
      ,[Last_PP_Date]
      ,[Days_Last_PP]
      ,[Last_PP_Date_Bucket]
      ,[Commission_Owner]
      ,[Installment_Amount]
      ,[Plan_Balance]
      ,[Last_Action_Date]
      ,[Country]
      ,[Country_Alpha2]
      ,[Days_Last_Actioned]
      ,[Last_Action_Date_Bucket]
      ,[3_Days_Not_Called]
      ,[3_Days_Not_Actioned]
      ,[New_Load_Not_Called]
      ,[30_Days_Not_Actioned]
      ,[AgencyCountrySpecific]
      ,[Agency]
      ,[Unit]
      ,[Plan_Status]
      ,[Principal_Value]
      ,[debt_amount]
      ,[Last_Task]
      ,[Last_Task_Date]
      ,[Product_Type]
      ,[Takeover_Memo]
  FROM [Report].[vw_Account_Breakdown_TH]
  --WHERE Base_Portfolio NOT IN ('AEON1 TH','AEON2 TH','AEON3 TH','SME1 TH','SME2 TH','TMB1 TH','TMB2 TH','KKP1 TH','BMW1 TH')
  --WHERE Base_Portfolio IN ('AEON1 TH','AEON2 TH','AEON3 TH')
  --WHERE Base_Portfolio IN ('SME 1 TH','SME2 TH','TMB1 TH','TMB2 TH')
  WHERE Base_Portfolio IN ('MONIX SVC TH','ULITE SVC TH','GRAB SVC TH','KLINE W SVC TH','KLINE B SVC TH','SEAMONEY SPL SVC TH','SEAMONEY BCL SVC TH','Minor SVC TH','ALPHA AMC SVC TH')
  AND Stage NOT IN ('Closed','Pending Close Review')
  ORDER BY Base_Portfolio, Last_Action_Date DESC